# Generated by Django 5.1.6 on 2025-03-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_textbook_checked_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('PHYS', 'Physics'), ('PHIL', 'Philosophy')], max_length=10),
        ),
    ]
