# Generated by Django 5.1.6 on 2025-04-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0009_alter_collection_allowed_patrons'),
        ('textbook', '0009_remove_library_textbooks_library_collections'),
    ]

    operations = [
    ]
