# Generated by Django 5.1.6 on 2025-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('patron', 'Patron'), ('librarian', 'Librarian')], default='patron', max_length=20),
        ),
    ]
