# Generated by Django 5.1.6 on 2025-02-23 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('PHYS', 'Physics')], max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published_date', models.DateField()),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('associated_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='textbook.class')),
            ],
        ),
    ]
