# Generated by Django 5.1.6 on 2025-03-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
