# Generated by Django 5.1.6 on 2025-03-16 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_alter_class_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='textbook_pictures/')),
                ('textbook', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textbook', to='textbook.textbook')),
            ],
        ),
    ]
