# Generated by Django 5.1.6 on 2025-03-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0004_textbookphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('PHYS', 'Physics'), ('PHIL', 'Philosophy'), ('APMA', 'Applied Math'), ('GERM', 'German'), ('ECE', 'Electrical and Computer Engineering')], max_length=10),
        ),
    ]
