# Generated by Django 5.1.6 on 2025-04-12 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0007_textbookrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allowed_patrons',
            field=models.ManyToManyField(related_name='allowed_collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
