# Generated by Django 5.1.6 on 2025-04-29 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0012_textbook_description_textbook_library_textbookrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
