# Generated by Django 5.1.6 on 2025-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0013_collectionrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequests',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10),
        ),
    ]
