# Generated by Django 5.1.6 on 2025-04-29 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0014_collectionrequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequests',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
